### PR TITLE
Fixed types on the db functions

### LINKED ISSUE #37: Bug with UserType info is prob dublicate
Prob dublicate userinfo is parse with from db queries

---

Image

### PR DESCRIPTION
**Pull request by Nicolai-Holmgaard**
This should fix the typescript errors

### CODE REVIEW

File: src/lib/server/db/index.ts [hunk 1]
```diff
@@ -3,48 +3,40 @@ import { drizzle } from "drizzle-orm/postgres-js";
...
+	return db.query.User.findFirst({
 		where: {
 			Id: Id
 		},
 		with: {
 			UserInfo: withUserInfo,
 			Course: true
 		}
-	});
+	}) as unknown as UserType;
```
Comment (Rasmkrog) [inline src/lib/server/db/index.ts]: what does this do?

File: src/lib/types.ts [hunk 2]
```diff
@@ -15,7 +15,7 @@ export interface UserInfo {
 	Gender: Genders;
 	Email: string;
 	PhoneNumber: string;
-	Birthdate: Date;
+	Birthdate: string;
```
Comment (Rasmkrog) [inline src/lib/types.ts]: Hvilket format, DD/MM/YYYY or MM/DD/YYYY?

**Review by Rasmkrog — COMMENTED** [review]
LGTM when the to things commented are fixed/explained

**Review by TobiasKaa — APPROVED** [review]
LGTM

**Review by Rasmkrog — APPROVED** [review]
LGTM 🍻
